import {Server} from "colyseus";
import {WebSocketTransport} from "@colyseus/ws-transport";
import {createServer} from "node:http";
import {ArenaRoom} from "./rooms/ArenaRoom.js";
import {BossRushRoom} from "./rooms/BossRushRoom.js";
const httpServer=createServer();
const gameServer=new Server({transport:new WebSocketTransport({server:httpServer})});
gameServer.define("arena",ArenaRoom);
gameServer.define("boss-rush",BossRushRoom);
const port=Number(process.env.PORT??2567);
httpServer.listen(port,()=>console.log("NEXO REALMS multiplayer server listening on http://localhost:"+port));
