import {Room,Client} from "colyseus";
import {Schema,type} from "@colyseus/schema";
import {SupabaseService} from "../services/SupabaseService.js";
type GameClass="cavaleiro"|"arqueiro"|"mago";type Action="attack"|"skill1"|"skill2"|"skill3";type Difficulty="normal"|"hard"|"nightmare";
const BOSSES=[{id:"warden-of-roots",name:"Aldren",hp:2200},{id:"iron-queen",name:"Veyra",hp:4200},{id:"eclipse-lord",name:"Noctis",hp:8000}];
const MULTIPLIER:Record<Difficulty,number>={normal:1,hard:1.55,nightmare:2.3};
export class BossRushState extends Schema{@type("string")playerId="";@type("string")userId="";@type("string")gameClass:GameClass="cavaleiro";@type("string")difficulty:Difficulty="normal";@type("number")bossIndex=0;@type("number")bossHp=2200;@type("number")bossMaxHp=2200;@type("number")score=0;@type("number")elapsed=0;@type("number")startedAt=0;@type("string")status="waiting";}
export class BossRushRoom extends Room<BossRushState>{
 maxClients=1;maxMessagesPerSecond=12;private nextActionAt=0;private db=new SupabaseService();
 async onAuth(_client:Client,_options:unknown,context:{token?:string}){if(!this.db.enabled)return{userId:"guest"};const user=context.token?await this.db.validateAccessToken(context.token):undefined;if(!user)throw new Error("Login necessário para ranking online.");return{userId:user.id};}
 onCreate(options:{difficulty?:Difficulty}={}){this.state=new BossRushState();this.state.difficulty=options.difficulty==="hard"||options.difficulty==="nightmare"?options.difficulty:"normal";this.setPatchRate(100);this.setSimulationInterval(()=>{if(this.state.status==="running")this.state.elapsed=Date.now()-this.state.startedAt;});this.onMessage("action",(client,payload:{action?:Action})=>{if(client.sessionId!==this.state.playerId||this.state.status!=="running")return;const action=payload?.action;if(!action||Date.now()<this.nextActionAt)return;const multipliers:Record<Action,number>={attack:1,skill1:2,skill2:2.6,skill3:3.2};const classBonus=this.state.gameClass==="mago"?1.08:this.state.gameClass==="arqueiro"?1.04:1;const damage=Math.max(1,Math.round(65*multipliers[action]*classBonus));this.nextActionAt=Date.now()+(action==="attack"?260:900);this.state.bossHp=Math.max(0,this.state.bossHp-damage);this.state.score+=Math.round(damage*10*(this.state.difficulty==="nightmare"?1.8:this.state.difficulty==="hard"?1.35:1));this.broadcast("hit-confirmed",{damage,bossHp:this.state.bossHp,bossIndex:this.state.bossIndex});if(this.state.bossHp===0)void this.finishBoss();});}
 onJoin(client:Client,options:{gameClass?:GameClass},auth:{userId:string}){this.state.playerId=client.sessionId;this.state.userId=auth.userId;this.state.gameClass=options?.gameClass==="arqueiro"||options?.gameClass==="mago"?options.gameClass:"cavaleiro";this.state.startedAt=Date.now();this.state.status="running";this.resetBoss(0);}
 async onLeave(){if(this.state.status==="running")this.state.status="finished";}
 private async finishBoss(){const timeBonus=Math.max(100,10000-Math.floor(this.state.elapsed/100));this.state.score+=timeBonus;if(this.state.bossIndex>=BOSSES.length-1){this.state.status="finished";this.broadcast("run-finished",{score:this.state.score,elapsed:this.state.elapsed,difficulty:this.state.difficulty});if(this.db.enabled){try{await this.db.insert("boss_rush_runs",{user_id:this.state.userId,season_id:process.env.GAME_SEASON_ID??"season-local",difficulty:this.state.difficulty,score:this.state.score,elapsed_ms:this.state.elapsed,bosses_defeated:BOSSES.length,validation_status:"validated"});}catch(error){console.error("boss rush persistence failed",error);}}return;}this.resetBoss(this.state.bossIndex+1);}
 private resetBoss(index:number){const boss=BOSSES[index];const hp=Math.round(boss.hp*MULTIPLIER[this.state.difficulty]);this.state.bossIndex=index;this.state.bossHp=hp;this.state.bossMaxHp=hp;}
}